server:  
  port: ${PORT:8090}

spring:  
  application:
    name: github-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  activemq:
    broker-url: tcp://172.31.88.3:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: 172.31.89.54
      port: 27017
      database: scmDetails
      repositories:
        enabled: true 

scm:
  github:
    commit:
      url: https://api.github.com/repos/userReplace/repo-replace/commits?sha=shaReplace
    commitPath:
      url: https://api.github.com/repos/userReplace/repo-replace/commits?path=folderName&recursive=1
    branch:
      url: https://api.github.com/repos/userReplace/repo-replace/branches
  gitlab:
    commit:
      url: https://api.github.com/repos/userReplace/repo-replace/commits
    commitPath:
      url: https://api.github.com/repos/userReplace/repo-replace/commits?path=folderName&recursive=1
    branch:
      url: https://api.github.com/repos/userReplace/repo-replace/branches
      

repos:
  environment: dev
  repo:
  - monorepo: true
    multirepo: false
    name: workspace-test
    projects:
    - name: folderone
      path: folderone
    - name: foldertwo
      path: foldertwo
  - monorepo: true
    multirepo: false
    name: sample-spring-microservices
    projects:
    - name: account-service
      path: account-service
    - name: customer-service
      path: customer-service
    - name: discovery-service
      path: discovery-service
    - name: gateway-service
      path: gateway-service
          